### ISSUE TITLE
auto-update of dependent settings in library mode editing of config?

### ISSUE THREAD

**Issue by ldwillia** [FitSNAP/FitSNAP#214]
It would be nice for using the library mode if you could update just config.sections['BISPECTRUM'].twojmax and it would auto-update (or have always be a function call) the dependent settings of config.sections['BISPECTRUM'].ncoeff and config.sections["BISPECTRUM"].blank2J. 
Similar for config.sections['CALCULATOR'].per_atom_energy and pt.fitsnap_dict['per_atom_energy'] and other settings that are always initialized together but can become decoupled when changing values manually.

**Comment by rohskopf** [comment]
The new API way is to just make multiple instances of `FitSnap` with different settings.

For example define a dictionary of settings:
```
settings = \
{
"BISPECTRUM":
    {
    "numTypes": 1,
    "twojmax": 6,
...
```
Then make an instance:
```
fs = FitSnap(settings)
```
Now if you wanna change the settings, just change the settings and make a new instance:
```
fs2 = FitSnap(settings2)
```
Or even overwrite the original instance.

This provides a lot of flexibility because you could have an instance purely for descriptor calculations, with some settings, then more instances that use that data with different solver settings.

**Comment by rohskopf** [comment]
Why not convert config to a dictionary then input to an instance? We don't supply a config->dict function since it shouldn't be much effort to define a dictionary in a script like here: 

https://github.com/FitSNAP/FitSNAP/blob/master/examples/library/ase/example1.py

**Comment by ldwillia** [comment]
Alright, my lazy self has got it. Code to transform fitsnap.in to settings dictionary with minimal effort.
```
import configparser
c = configparser.ConfigParser()
c.read("fitsnap.in")
settings = {s:dict(c.items(s)) for s in c.sections()}
```

**Comment by rohskopf** [comment]
That is a helpful snippet, thank you!
