### ISSUE TITLE
Number of angular momenta in 4-body ACE coefficient

### ISSUE THREAD

**Issue by IlgarBaghishov** [FitSNAP/FitSNAP#222]
When I look at pot.acecoeff file that has all ACE coefficients, I can't understand why is there 4 angular momenta in the 4-body term in ACE. I would expect to have 3 radial values and 3 angular (n1, n2, n3 and l1, l2, l3) but there are four of l values (l1, l2, l3, l4).
For example, coefficient number 49 which is the first 4-body term for me is B[49, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0]. Basically, what I am trying to understand is why there are four zeros at the end. Shouldn't there be 3 of them?

**Comment by rohskopf** [comment]
This is a great question for @jmgoff

**Comment by jmgoff** [comment]
This is a good question and I realize now that the docs do not go into this too much. My bad. Here is a potentially too lengthy explanation for those extra angular momenta.

The way the labels for the N-bond ACE descriptors are defined are chemical index of the central atom, u0, then chemical indices for other atom in the N bonds, radial indices for the N bonds, angular indices for the N bonds, and then intermediate angular indices (when applicable). There are N-2 intermediate angular indices for descriptors with rank N>=3. For ranks >=3, you will find these intermediate indices after the N angular indices for the bonds. In general, the descriptor  labels will have the form:
u0, u1, u2, ... uN, n1,n2,... nN, l1,l2,... lN, { ... L(N-3), L(N-2) }

For this example:
0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0
u0, u1, u2, u3, n1, n2, n3, l1, l2, l3, L1

For the rank 4 you may see something like:
0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0
u0, u1, u2, u3, u4, n1, n2, n3, n4, l1, l2, l3, l4, L1, L2

and so on. These intermediate angular momenta are needed to unambiguously define the ACE descriptors and are used when we reduce the products of more than 3 spherical harmonics (as we are doing in the construction of these higher rank ACE descriptors). We can only reduce two spherical harmonics at a time, so we have to use 'intermediates'. In a cartoon fashion, we are doing something like this:
<img width="801" alt="Screenshot 2023-07-07 at 4 32 31 PM" src="https://github.com/FitSNAP/FitSNAP/assets/34103038/f7e73732-7d58-4b79-9169-f754e62b5151">
where L_R is 0 in our case so that our descriptors do not change values when the system is rotated.

I will work on adding information like this to the docs, but I'm happy to address any other questions or concerns until then.

**Comment by IlgarBaghishov** [comment]
Thank you so much! This is much more clear now. If you don't mind, I have a couple of additional questions.

I understand that we need it to construct higher rank ACE descriptors but what do you mean by unambiguously defining the ACE descriptors? Can we have a situation where we have the same l1, l2, ... lN but different { ... L(N-3), L(N-2) }? Aren't ACE descriptors already unambiguously defined by the set of chemical, radial, and angular indices? 

My second question would be how these L indices are calculated. Is it always like this: L1=l1+l2 and L2=l3+l4? The reason why I am asking is that I have this descriptor for my 3-body term:
B[62, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2]
and I have  this for 4-body:
B[170, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4] 
In the 3-body case, L1 is 2 and L1=l1+l2 does not apply
but in the 4-body term, L1=l1+l2 and L2=l3+l4 formulas apply. 
You can also just refer me to a paper or a source where this is explained.

Thanks again for the help!

**Comment by jmgoff** [comment]
This is a great question as well, and it has presented a subtle challenge in the ACE community for a while. There are a few things that go into choosing intermediates. If interested in all of the dirty details, you can read our new arXiv update [here](https://arxiv.org/abs/2208.01756v2) that explains it. Either way, a summary is probably due in our docs so I’ll give a brief one here as a start.

In short, the intermediates are chosen based on triangle conditions and parity constraints. The problem is that if one uses all sets of intermediates obeying these triangle conditions, then some of the ACE descriptors are linearly dependent. For this reason, recursion relationships are used to obtain a set of linearly independent ACE descriptors. 

Until now, numerical SVD has been used to eliminate the extra linearly dependent descriptors. The arXiv linked above details an analytical approach.

The figure attached goes through gives more of the details/steps to summarize how to choose the right ACE descriptors and shows how it is done for your B[170, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4], which is an excellent example to demonstrate.  

![‎ACE_intermediates ‎001](https://github.com/FitSNAP/FitSNAP/assets/34103038/c6d03ff6-a270-4a3f-9558-48a622aa5bac)

**Comment by IlgarBaghishov** [comment]
Thank you so much for the detailed explanation and references! I understand it way better now and I will go through the references to understand the details better.
