### ISSUE TITLE
Quadratic SNAP Flag Resulting in ValueError

### ISSUE THREAD

**Issue by dft-dutoit** [FitSNAP/FitSNAP#68]
Upon attempting a multi-element run with the quadratic flag enabled, a ValueError is produced of the form "cannot reshape array"

The quadratic example with Ta works flawlessly, and upon creating my own input files for other single element systems I find no problems. However, when attempting to edit the multi-element potentials, or create my own, the quadratic flag produces the cannot reshape array error.

As of right now I am experimenting with simply having the potentials fitted, and all hyperparameters are placeholders. I am assuming this is user error, but I cannot find a solution for multi-element systems after attempting various different flag options while qSNAP is enabled.

Is this a limitation that I am unaware of? Or should the quadratic flag be working in this case?

```
[BISPECTRUM]
numTypes = 3
twojmax = 6 6 6
rcutfac = 5
rfac0 = 0.99363
rmin0 = 0.0
wj = 1 1 1
radelem = 0.5 0.7 0.6
type = Li P Si
wselfallflag = 1
chemflag = 1
bzeroflag = 1
bnormflag = 0
quadraticflag = 1

[CALCULATOR]
calculator = LAMMPSSNAP
energy = 1
force = 1
stress = 1

[ESHIFT]
#Li = -197.6557135484
#Si = -163.2216433412
#P = -214.0212035722
Li = 0.0
P = 0.0
Si = 0.0


[SOLVER]
solver = SVD
compute_testerrs = 1
detailed_errors = 1

[SCRAPER]
scraper = XYZ

[PATH]
dataPath = JSON

[OUTFILE]
metrics = LSP_metrics.md
potential = LSP_pot

[REFERENCE]
units = metal
atom_style = atomic
pair_style = hybrid/overlay zero 10.0 zbl 2.0 4.8
pair_coeff1 = * * zero
pair_coeff2 = 1 1 zbl 3.0 3.0
pair_coeff3 = 1 2 zbl 3.0 15.0
pair_coeff4 = 1 3 zbl 3.0 14.0
pair_coeff5 = 2 2 zbl 15.0 15.0
pair_coeff6 = 2 3 zbl 15.0 14.0
pair_coeff7 = 3 3 zbl 14.0 14.0

[GROUPS]
# name size eweight fweight vweight
group_sections = name training_size testing_size eweight fweight vweight
group_types = str float float float float float
smartweights = 0
test_3 =  1.0   0.0         100         1.0         1.00E-12

[EXTRAS]
dump_descriptors = 0
dump_truth = 0
dump_weights = 0

[MEMORY]
override = 0
```

**Comment by charlessievers** [comment]
#69 should fix half of this problem, i.e. non-explicit multielement qsnap. I will note that quadratic + chemsnap is not a well tested feature and has an excessive number of bispectrum coefficients. My recommendation would be to either use just chemsnap or just quadratic snap. If you are going to use quadratic snap, you should use the version in #69 because there was a bug that prevented the use of non-explicit multielement qsnap. (chemsnap = explicit multielement snap) Also, if you are using XYZ scraper and have non orthorhombic cells, you may want to include the bug fix from #66.
