### ISSUE TITLE
How to interface with Dakota?

### ISSUE THREAD

**Issue by Rana-Phy** [FitSNAP/FitSNAP#72]
Dear Developers,

Thanks for fitsnap. Is there any technical document to optimize cuttoff and weights?

**Comment by mitwood** [comment]
Greetings Rana-Phy,
Thanks for your interest in FitSNAP. Since this is more of a DAKOTA support question I would suggest you head to dakota.sandia.gov to see their documentation. However, please follow up with me by sending me an email at mitwood*at*sandia.gov and I can send a skeleton version of a DAKOTA optimization that uses FitSNAP. 

We do plan to implement some optimization features directly into FitSNAP, but they will not be as universal and robust as DAKOTA.
